from __future__ import annotations

from .models import ExtensionPoint, Invariant


def invariants() -> tuple[Invariant, ...]:
    return (
        Invariant("RE-C-001", "Immutable Canonical Contracts", "Canonical reasoning inputs and outputs are immutable value objects.", "Immutability preserves replayability, auditability, and fingerprint integrity.", ("EvidenceItem", "Hypothesis", "ReasoningRequest", "PlanningRecommendation", "ReasoningResult"), "Canonical contracts remain frozen dataclasses or enforce equivalent immutability."),
        Invariant("RE-C-002", "Deterministic Core", "Equivalent canonical requests processed by the same engine version produce equivalent canonical results.", "Reasoning must be reproducible and testable.", ("ReasoningEngine", "ReasoningResult"), "Repeated executions produce identical canonical serialization and fingerprints."),
        Invariant("RE-C-003", "Explicit Evidence", "Reasoning may assess only evidence explicitly present in ReasoningRequest.", "Hidden retrieval would compromise explainability.", ("ReasoningRequest", "ReasoningEngine", "EvidenceItem"), "Core reasoning modules perform no direct retrieval or network access."),
        Invariant("RE-C-004", "Knowledge Boundary Isolation", "External knowledge enters reasoning through KnowledgeEvidenceAdapter.", "The adapter protects the reasoning core from retrieval schema drift.", ("KnowledgeEvidenceAdapter", "EvidenceItem"), "Pipeline inputs to reasoning are canonical EvidenceItem objects."),
        Invariant("RE-C-005", "Thin Composition Pipeline", "KnowledgeReasoningPipeline coordinates dedicated components and does not absorb their responsibilities.", "Thin orchestration preserves replaceability and testability.", ("KnowledgeReasoningPipeline",), "Search, adaptation, generation, and reasoning remain delegated."),
        Invariant("RE-C-006", "Inference and Planning Separation", "Reasoning may recommend actions but does not create, authorize, or execute operational plans.", "Recommendations are advisory outputs, not executive authority.", ("ReasoningEngine", "PlanningRecommendation", "ReasoningResult"), "Core reasoning performs no mission or planning state mutation."),
        Invariant("RE-C-007", "Auditable Trace", "Completed reasoning results expose an ordered trace of material reasoning stages.", "Operators require transparent and reviewable reasoning.", ("ReasoningEngine", "ReasoningResult"), "Trace ordering is stable and includes validation and conclusion selection."),
        Invariant("RE-C-008", "Stable Identifier Derivation", "Derived identifiers use stable canonical inputs.", "Stable identifiers enable replay and provenance.", ("EvidenceItem", "ReasoningRequest", "ReasoningResult"), "Identifiers do not depend on time, randomness, memory addresses, or unordered traversal."),
        Invariant("RE-C-009", "No Hidden Executive Authority", "Reasoning recommends; executive layers authorize; execution occurs elsewhere.", "Authority boundaries must remain explicit.", ("ReasoningEngine", "KnowledgeReasoningPipeline"), "Reasoning modules expose no mission execution side effects."),
        Invariant("RE-C-010", "Versioned Evolution", "Compatibility-affecting contract, fingerprint, ranking, or result changes require explicit versioning and migration.", "Historical results must remain interpretable.", ("ReasoningEngine", "ReasoningRequest", "ReasoningResult"), "Architecture-impacting changes include regression fixtures and version updates."),
    )


def extension_points() -> tuple[ExtensionPoint, ...]:
    return (
        ExtensionPoint("ReasoningSession", "Provide persistent lifecycle and executive context around canonical reasoning executions.", ("ReasoningRequest", "ReasoningEngine", "ReasoningResult", "KnowledgeReasoningPipeline"), ("Lifecycle state", "Mission context", "Reasoning budgets", "Attempt history", "Review state"), ("Replacing canonical request or result contracts", "Hidden inference", "Mutating historical results"), "Genesis II", "Wrap existing deterministic execution without changing request/result semantics."),
        ExtensionPoint("EvidenceProvenance", "Represent structured origin, admission, trust, and knowledge lineage.", ("KnowledgeEvidenceAdapter", "EvidenceItem"), ("Knowledge object identity", "Chunk identity", "Admission state", "Trust state", "Acquisition lineage"), ("Inference", "Conclusion selection", "Mutable source rewriting"), "Genesis III", "Preserve existing source references during migration."),
        ExtensionPoint("ExecutiveReasoningGovernance", "Apply explicit executive directives and reasoning policy.", ("ReasoningSession", "ReasoningEngine"), ("Reasoning mode", "Depth budgets", "Minimum confidence", "Independent-source requirements", "Human-review requirements"), ("Silently changing evidence", "Overwriting conclusions", "Executing recommendations"), "Genesis IV", "Governance must be explicit and serialized."),
        ExtensionPoint("CompetingHypothesisEngine", "Expand generation and comparison of alternative explanations.", ("Hypothesis", "ReasoningEngine"), ("Alternative generation", "Mutual-exclusion groups", "Assumption discovery", "Counter-hypothesis generation"), ("Hidden retrieval", "Mission execution", "Non-auditable selection"), "Genesis V", "Generated hypotheses remain immutable canonical contracts."),
        ExtensionPoint("AdaptiveReasoningController", "Choose approved reasoning strategies and depth within explicit budgets.", ("ReasoningSession", "ReasoningEngine"), ("Strategy selection", "Depth escalation", "Early stopping", "Budget accounting"), ("Unbounded recursion", "Unrecorded strategy changes", "Bypassing executive limits"), "Genesis VI", "Adaptation decisions remain traceable and deterministic in deterministic mode."),
        ExtensionPoint("OutcomeCalibration", "Compare prior confidence and recommendations against observed outcomes.", ("ReasoningResult", "ReasoningSession"), ("Calibration metrics", "Confidence error analysis", "Recommendation outcome linkage"), ("Mutating historical results", "Automatic ungoverned policy changes"), "Genesis VII", "Calibration references immutable historical results."),
        ExtensionPoint("LearningFeedback", "Propose governed improvements from calibrated historical outcomes.", ("OutcomeCalibration", "ExecutiveReasoningGovernance"), ("Improvement proposals", "Trust adjustment proposals", "Regression fixture generation"), ("Self-modifying production code", "Unapproved policy mutation"), "Genesis VIII", "Learning remains reviewable, reversible, and versioned."),
    )
