"""
Read-only source-collection planning handler.

Phase VI-D2 resolves one source_collection object and creates a deterministic
direct-child expansion plan.

Knowledge Registry SQL is owned by KnowledgeRegistryRepository. This handler
contains no direct database queries and performs no registry or queue writes.
"""

from __future__ import annotations

from typing import Any

from knowledge_engine.assimilation.collection_plan import (
    CollectionExpansionPlanner,
)
from knowledge_engine.assimilation.handlers.base import (
    AssimilationHandler,
)
from knowledge_engine.assimilation.repositories import (
    KnowledgeRegistryRepository,
)


class SourceCollectionHandler(AssimilationHandler):
    """Plan the direct children of one registered source collection."""

    object_type = "source_collection"

    def __init__(
        self,
        db: Any,
        *,
        planner: CollectionExpansionPlanner | None = None,
        registry_repository: KnowledgeRegistryRepository | None = None,
    ):
        self.db = db

        self.registry_repository = (
            registry_repository
            or KnowledgeRegistryRepository(db)
        )

        self.planner = (
            planner
            or CollectionExpansionPlanner()
        )

    def plan(
        self,
        *,
        object_uuid: str,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """
        Confirm that the handler is prepared to plan this object.

        The actual deterministic filesystem plan is currently generated by
        execute(), preserving the verified Phase VI-D2 behavior.
        """

        del kwargs

        return {
            "status": "planning_ready",
            "object_uuid": object_uuid,
            "object_type": self.object_type,
        }

    def verify(
        self,
        *,
        object_uuid: str,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """Verify that a matching source_collection is registered."""

        del kwargs

        collection = self._load_collection(object_uuid)

        if collection is None:
            return {
                "status": "not_found",
                "verified": False,
                "object_uuid": object_uuid,
                "object_type": self.object_type,
                "message": (
                    "No registered source_collection object was found."
                ),
            }

        return {
            "status": "verified",
            "verified": True,
            "object_uuid": object_uuid,
            "object_type": self.object_type,
            "object_path": collection["object_path"],
        }

    def execute(
        self,
        *,
        object_uuid: str,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """Create a deterministic read-only direct-child expansion plan."""

        del kwargs

        collection = self._load_collection(object_uuid)

        if collection is None:
            return {
                "processed": 0,
                "failed": 1,
                "object_uuid": object_uuid,
                "object_type": self.object_type,
                "status": "not_found",
                "message": (
                    "No registered source_collection object was found "
                    f"for UUID {object_uuid!r}."
                ),
            }

        try:
            plan = self.planner.plan(
                object_uuid=object_uuid,
                collection_path=collection["object_path"],
            )
        except (
            FileNotFoundError,
            NotADirectoryError,
            OSError,
        ) as exc:
            return {
                "processed": 0,
                "failed": 1,
                "object_uuid": object_uuid,
                "object_type": self.object_type,
                "status": "planning_failed",
                "message": str(exc),
                "error_type": type(exc).__name__,
            }

        return {
            "processed": 0,
            "failed": 0,
            "object_uuid": object_uuid,
            "object_type": self.object_type,
            "status": "planned",
            "message": (
                "Source collection direct-child expansion plan created. "
                "No registry changes were made."
            ),
            "plan": plan.to_dict(),
        }

    def recover(
        self,
        *,
        object_uuid: str,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """Report that read-only planning requires no recovery action."""

        del kwargs

        return {
            "status": "no_recovery_required",
            "object_uuid": object_uuid,
            "object_type": self.object_type,
        }

    def report(
        self,
        *,
        object_uuid: str,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """Return a minimal source-collection handler report."""

        del kwargs

        collection = self._load_collection(object_uuid)

        return {
            "status": (
                "report_available"
                if collection is not None
                else "not_found"
            ),
            "object_uuid": object_uuid,
            "object_type": self.object_type,
            "registered": collection is not None,
            "object_path": (
                collection["object_path"]
                if collection is not None
                else None
            ),
        }

    def _load_collection(
        self,
        object_uuid: str,
    ) -> dict[str, Any] | None:
        """Load one source collection through the repository abstraction."""

        collection = self.registry_repository.get_source_collection(
            object_uuid=object_uuid,
        )

        if collection is None:
            return None

        return collection.to_dict()
