"""Genesis IV cognition-domain public API.

The cognition layer transforms represented knowledge into deterministic,
immutable cognitive objects without performing planning or execution.
"""

from .confidence import (
    ConfidenceAssessment,
    ConfidenceFactors,
    ExtractionQuality,
    SourceReliability,
    assess_confidence,
    clamp_confidence,
    confidence_band,
    confidence_for_direct_source,
)
from .contracts import (
    GENESIS_IV_A1_SCHEMA_VERSION,
    Metadata,
    Observation,
    ObservationValue,
    SourceReference,
    normalize_confidence,
    normalize_metadata,
)
from .enums import (
    CognitiveObjectKind,
    ConfidenceBand,
    ObservationOrigin,
    ObservationPolarity,
    ObservationValueKind,
)
from .errors import (
    CognitionError,
    CognitionIdentifierError,
    CognitionSerializationError,
    CognitionValidationError,
    UnsupportedCognitiveObjectError,
)
from .extraction import (
    ExtractionPattern,
    ExtractionResult,
    ExtractionSource,
    ObservationCandidate,
    extract_candidates,
    extract_many,
    structured_candidate,
)
from .identifiers import (
    make_cognition_id,
    normalize_kind,
    parse_cognition_id,
    validate_cognition_id,
    verify_cognition_id,
)
from .normalization import (
    NormalizedObservationValue,
    NormalizedQuantity,
    infer_value_kind,
    normalize_boolean_text,
    normalize_concept,
    normalize_decimal_text,
    normalize_display_text,
    normalize_identifier_token,
    normalize_integer_text,
    normalize_observation_value,
    normalize_unicode,
    normalize_unit,
    normalize_whitespace,
    parse_quantity,
)
from .observation import (
    ObservationBatch,
    ObservationConstruction,
    ObservationEngine,
    build_observation,
    observe_source,
)
from .serialization import (
    canonical_fingerprint,
    canonical_json,
    canonicalize,
    decimal_to_string,
    pretty_json,
)
from .validation import (
    validate_cognitive_object,
    validate_observation,
    validate_observation_value,
    validate_source_reference,
)

__all__ = [
    "GENESIS_IV_A1_SCHEMA_VERSION",
    "Metadata",
    "Observation",
    "ObservationValue",
    "SourceReference",
    "CognitiveObjectKind",
    "ConfidenceBand",
    "ObservationOrigin",
    "ObservationPolarity",
    "ObservationValueKind",
    "CognitionError",
    "CognitionIdentifierError",
    "CognitionSerializationError",
    "CognitionValidationError",
    "UnsupportedCognitiveObjectError",
    "ConfidenceAssessment",
    "ConfidenceFactors",
    "ExtractionQuality",
    "SourceReliability",
    "ExtractionPattern",
    "ExtractionResult",
    "ExtractionSource",
    "ObservationCandidate",
    "NormalizedObservationValue",
    "NormalizedQuantity",
    "ObservationBatch",
    "ObservationConstruction",
    "ObservationEngine",
    "assess_confidence",
    "build_observation",
    "canonical_fingerprint",
    "canonical_json",
    "canonicalize",
    "clamp_confidence",
    "confidence_band",
    "confidence_for_direct_source",
    "decimal_to_string",
    "extract_candidates",
    "extract_many",
    "infer_value_kind",
    "make_cognition_id",
    "normalize_boolean_text",
    "normalize_concept",
    "normalize_confidence",
    "normalize_decimal_text",
    "normalize_display_text",
    "normalize_identifier_token",
    "normalize_integer_text",
    "normalize_kind",
    "normalize_metadata",
    "normalize_observation_value",
    "normalize_unicode",
    "normalize_unit",
    "normalize_whitespace",
    "observe_source",
    "parse_cognition_id",
    "parse_quantity",
    "pretty_json",
    "structured_candidate",
    "validate_cognition_id",
    "validate_cognitive_object",
    "validate_observation",
    "validate_observation_value",
    "validate_source_reference",
    "verify_cognition_id",
]
